# Sidebar widget configurations
# http://ppoffice.github.io/hexo-theme-icarus/categories/Widgets/
widgets:
  - position: left
    type: categories
  - position: left
    type: toc
  - position: left
    type: recent_posts
